### ISSUE TITLE
Fix build deployment failures on fly

### ISSUE THREAD

**Issue by vipulnsward** [saeloun/miru-web#1875]
https://github.com/saeloun/miru-web/actions/runs/9871694613/job/27260152767

**Comment by apoorv1316** [comment]
@vipulnsward The deployment was failing because app builder needed more memory. Fly creates them while deploying the app and they are auto destroyed and free to use. I've upgraded the builder machine memory and the deployment step is passing. I've verified it by doing manual deployment from my machine and with GitHub auto deploy in this PR. https://github.com/saeloun/miru-web/actions/runs/9905084976/job/27363852209
